ARDUINO_DIR  = /usr/share/arduino
ARDMK_DIR    = /usr/share/arduino
USER_LIB_PATH = /home/pi/piBoxBot/sketches/libraries
ARDUINO_LIB_PATH = /home/pi/piBoxBot/sketches/libraries
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

include /usr/share/arduino/Arduino.mk
