### SYSTEM ###

alias cc='clear'
alias offf='sudo shutdown -h now'
alias rbt='sudo reboot'
alias srv_s='sudo systemctl status bot.service climate.service sensors.service lights.service'
alias font='sudo dpkg-reconfigure console-setup'

alias rconf='sudo raspi-config'
alias wlan='python ~/piBoxBot/py/wlan.py'
alias remHost='ssh-keygen -f "/home/pi/.ssh/known_hosts" -R "$1"'
alias 1='cd ~/piBoxBot/ && cc && s'
alias nn='sudo nano'

### HOSTS ###

#alias piData='ssh pi@piData.local'
alias piData='ssh pi@192.168.31.187'
#alias piDataPhotos='scp -r pi@piData.local:/home/pi/cam/ /home/pi/Pictures/'
#alias piDataPhotos='scp -r pi@192.168.31.187:/home/pi/cam/ /home/pi/Pictures/piData/'

#alias piMedia='ssh pi@piMedia.local'
#alias piMedia='ssh pi@192.168.31.158'
#alias piMediaPhotos='scp -r pi@piMedia.local:/home/pi/cam/ /home/pi/Pictures/'

#alias piTerminal='ssh pi@piTerminal.local'
#alias piTerminal='ssh pi@192.168.31.56'


### GIT ###

alias g='git'
alias s='git status'
alias ddd='git diff'
alias br='git branch'
alias fetch='git fetch --all'
alias co='git checkout'

alias ci='git commit -m"$1"'
alias push='git push origin $1'
alias pull='git pull origin $1'

alias m='git pull origin master'
alias master='git push origin master'
alias d='git pull origin dev'
alias dev='git push origin dev'

### RPi ###
alias piPhotos='scp -r pi@piMedia.local:/home/pi/cam/ /Users/rx/Pictures/'

alias flashHelp='print "FS [Free Space|HFS+|FAT|FAT32|ExFAT]" && diskutil list'
alias flash='diskutil eraseDisk "$1" "$2" /dev/"$3"'

alias g='git'
alias s='git status'
alias d='git diff'
alias br='git branch'
alias ci='git commit -m"$1"'
alias co='git checkout'
alias fetch='git fetch --all'
alias m='git pull origin master'
alias d='git pull origin dev'
alias dev='git push origin dev'
alias push='git push origin $1'

alias storybook='cd ~/Applications/app && fetch && m && br && s && yarn && yarn storybook'
alias app='cd && cd deemAPP && br && s && fetch && m && yarn && yarn start'
alias gql='cd && cd deemGQL && br && s && fetch && m && yarn && yarn start'
