alias piMedia='ssh pi@piMedia.local'
alias piPhotos='scp -r pi@pi.local:/home/pi/cam/ /Users/rom/Documents/'
piMedia

alias cc='clear'
alias offf='sudo shutdown -h now'

alias g='git'
alias s='git status'
alias m='git pull origin master'
alias master='git push origin master'
alias d='git pull origin dev'
alias dev='git push origin dev'

alias srv_s='sudo systemctl status bot.service climate.service sensors.service lights.service'

alias piData='ssh pi@piData.local'
alias piMedia='ssh pi@piMedia.local'
alias piDataPhotos='scp -r pi@192.168.31.187:/home/pi/cam/ /home/pi/Pictures/piData'


alias g='git'
alias s='git status'
alias br='git branch'
alias ci='git commit -m"$1"'
alias co='git checkout'
alias fetch='git fetch --all'
alias m='git pull origin master'
alias d='git pull origin dev'
alias dev='git push origin dev'
alias push='git push origin $1'

alias storybook='cd ~/Applications/app && fetch && m && br && s && yarn && yarn storybook'

