alias piMedia='ssh pi@piMedia.local'
alias piPhotos='scp -r pi@pi.local:/home/pi/cam/ /Users/rom/Documents/'

alias cc='clear'
alias offf='sudo shutdown -h now'

alias g='git'
alias s='git status'
alias d='git diff'
alias ci='git commit'
alias fetch='git fetch --all'
alias m='git pull origin master'
alias master='git push origin master'
alias d='git pull origin dev'
alias dev='git push origin dev'

alias srv_s='sudo systemctl status bot.service climate.service sensors.service lights.service'
