# ARDUINO_DIR  = /Applications/Arduino.app/Contents/Java/hardware/arduino
# ARDMK_DIR  = /Applications/Arduino.app/Contents/Java/hardware/arduino
# USER_LIB_PATH = /Users/rx/Documents/Arduino
# ARDUINO_LIB_PATH = /Users/rx/Documents/Arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/tty.usbmodem14101

include /Users/rx/Documents/Arduino/Arduino.mk


