USER_LIB_PATH = /home/pi/piBoxBot/sketches/libraries
BOARD_TAG     = uno
# MONITOR_PORT  = /dev/ttyACM0
# ARDUINO_PORT  = /dev/ttyACM0
# MONITOR_PORT  = /dev/ttyACM0
# ARDUINO_PORT  = /dev/ttyACM0
MONITOR_PORT  = /dev/tty.usbmodem14201
ARDUINO_PORT  = /dev/tty.usbmodem14201

include /usr/share/arduino/Arduino.mk
