# ARDUINO_DIR  = /Applications/Arduino.app/Contents/Java/hardware/arduino
# ARDMK_DIR  = /Applications/Arduino.app/Contents/Java/hardware/arduino
USER_LIB_PATH = /home/pi/piBoxBot/sketches/libraries
# ARDUINO_LIB_PATH = /home/pi/piBoxBot/sketches/libraries
BOARD_TAG    = leonardo
MONITOR_PORT = /dev/ttyACM0
ARDUINO_PORT = /dev/ttyACM0

include /usr/share/arduino/Arduino.mk
