struct sensor {
  int pin;
  String label;
};

const int LED_OFFSET = 100;
const int PAUSE = 750;
const int REST = 1000;

struct sensor PIRAHNIA_2 = { 2, "|ed" };
struct sensor PIRAHNIA_3 = { 3, "||ed" };
struct sensor PIRAHNIA_4 = { 4, "|||ed" };
struct sensor PIRAHNIA_5 = { 5, "||||ed" };
struct sensor PIRAHNIA_6 = { 6, "|||||ed" };

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  pinMode(PIRAHNIA_2.pin, OUTPUT);
  pinMode(PIRAHNIA_3.pin, OUTPUT);
  pinMode(PIRAHNIA_4.pin, OUTPUT);
  pinMode(PIRAHNIA_5.pin, OUTPUT);
  pinMode(PIRAHNIA_6.pin, OUTPUT);

  digitalWrite(LED_BUILTIN, LOW);
}

void loop() {
  delay(PAUSE);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  /* ======================================================== */
  digitalWrite(LED_BUILTIN, HIGH);
  delay(LED_OFFSET);
  digitalWrite(LED_BUILTIN, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_2.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_3.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_4.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_5.pin, LOW);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, HIGH);
  delay(LED_OFFSET);
  digitalWrite(PIRAHNIA_6.pin, LOW);
  delay(LED_OFFSET);

  delay(REST);
}
